[package]
name = "timings"
version = "0.1.0"
edition = "2021"

[features]
default = ["formatting"]
formatting = ["tabled"]

[dependencies]
flume = "0.10.12"
tabled = { version = "0.7.0", optional = true }
parking_lot = { version = "0.12.1", features = ["arc_lock"] }
